### ISSUE TITLE
Incorrect decoding of partition manifest

### ISSUE THREAD

**Issue by VladLazar** [jcsp/segment_toy#2]
`decode-partition-manifest` does not decode the attached `man.bin` correctly. It produces `result.json` instead of `expected.json`.

**Comment by VladLazar** [comment]
[files.tar.gz](https://github.com/jcsp/segment_toy/files/11509197/files.tar.gz)

**Comment by andijcr** [comment]
[sorted_json.zip](https://github.com/jcsp/segment_toy/files/11509514/sorted_json.zip)
sorted by keys, for easier diffing
